name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  sonar:    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Install Sonar Scanner
      shell: pwsh
      run: |
        New-Item -Path ./.sonar/scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build And Test
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        .\.sonar\scanner\dotnet-sonarscanner begin /k:"marcelocasteloio_ShopDemo" /o:"marcelocasteloio" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="tst/**" /d:sonar.exclusions="tst/**"
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./tst/Tests.UnitTests/ShopDemo.Tests.UnitTests.csproj
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  multant-tests:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Install Stryker
      shell: pwsh
      run: |
        dotnet tool install -g dotnet-stryker
    - id: run-multant-tests
      name: Run Multant Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        cd ./tst/Tests.UnitTests
        dotnet stryker
        cd ../..

        $matches = Get-ChildItem -Path . -Filter "mutation-report.html" -Recurse | %{$_.FullName}
        if ($matches) {
            $firstMatch = $matches
            Write-Output "First match: $firstMatch"
        } else {
            Write-Output "No matches found."
        }
        echo "$firstMatch" > multant-test-report-path.txt
        echo "MULTANT_TEST_REPORT=TesteTesteTeste" >> $GITHUB_ENV
        echo "$MULTANT_TEST_REPORT"
    - name: Check Mutant Report Path
      run: echo "$env:MULTANT_TEST_REPORT"
    - name: Archive Multant Test
      uses: actions/upload-artifact@v3
      with:
        name: multant-test-report
        path: "$(cat multant-test-report-path.txt)"
    - name: HTML Preview
      id: html_preview
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: "$(cat multant-test-report-path.txt)"
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" >> "$GITHUB_ENV"
    - name: Use the value
      id: step_two
      run: |
  
        echo "${{ env.action_state }}" # This will output 'yellow'
